In [ ]:
import pandas as pd
import os

for file in os.listdir('/content'):
    if file.endswith('.csv'):
        print(file)

Employee_Attrition_3000_Synthetic_Records.csv.csv

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Employee_Attrition_3000_Synthetic_Records.csv.csv')

print("Dataset loaded successfully!")
print("Number of rows and columns:", df.shape)

display(df.head())

Dataset loaded successfully!
Number of rows and columns: (3000, 12)

,Age,Attrition,Department,Gender,JobRole,MonthlyIncome,JobSatisfaction,OverTime,TotalWorkingYears,YearsAtCompany,WorkLifeBalance,YearsInCurrentRole
0,38,No,Research & Development,Female,Manufacturing Director,7711,1,No,11,0,2,0
1,44,No,Research & Development,Male,Manufacturing Director,6560,4,No,10,0,1,0
2,54,No,Research & Development,Male,Research Scientist,9184,3,No,16,8,3,3
3,35,No,Human Resources,Female,Manager,5282,4,No,13,12,4,2
4,34,No,Sales,Female,Sales Executive,5970,4,No,6,3,3,3

In [ ]:
print("Column Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Information:")
print(df.info())

Column Names:
['Age', 'Attrition', 'Department', 'Gender', 'JobRole', 'MonthlyIncome', 'JobSatisfaction', 'OverTime', 'TotalWorkingYears', 'YearsAtCompany', 'WorkLifeBalance', 'YearsInCurrentRole']

Missing Values:
Age                   0
Attrition             0
Department            0
Gender                0
JobRole               0
MonthlyIncome         0
JobSatisfaction       0
OverTime              0
TotalWorkingYears     0
YearsAtCompany        0
WorkLifeBalance       0
YearsInCurrentRole    0
dtype: int64

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 3000 non-null   int64
 1   Attrition           3000 non-null   object
 2   Department          3000 non-null   object
 3   Gender              3000 non-null   object
 4   JobRole             3000 non-null   object
 5   MonthlyIncome       3000 non-null   int64
 6   JobSatisfaction     3000 non-null   int64
 7   OverTime            3000 non-null   object
 8   TotalWorkingYears   3000 non-null   int64
 9   YearsAtCompany      3000 non-null   int64
 10  WorkLifeBalance     3000 non-null   int64
 11  YearsInCurrentRole  3000 non-null   int64
dtypes: int64(7), object(5)
memory usage: 281.4+ KB
None

In [ ]:
print("Attrition Values:")
print(df["Attrition"].value_counts())

print("\nAttrition Percentage:")
print(df["Attrition"].value_counts(normalize=True) * 100)

Attrition Values:
Attrition
No     2250
Yes     750
Name: count, dtype: int64

Attrition Percentage:
Attrition
No     75.0
Yes    25.0
Name: proportion, dtype: float64

In [ ]:
# Separate input data and output data

X = df.drop("Attrition", axis=1)
y = df["Attrition"]

print("Input data shape:", X.shape)
print("Output data shape:", y.shape)

print("\nInput data:")
display(X.head())

print("\nOutput data:")
display(y.head())

Input data shape: (3000, 11)
Output data shape: (3000,)

Input data:

,Age,Department,Gender,JobRole,MonthlyIncome,JobSatisfaction,OverTime,TotalWorkingYears,YearsAtCompany,WorkLifeBalance,YearsInCurrentRole
0,38,Research & Development,Female,Manufacturing Director,7711,1,No,11,0,2,0
1,44,Research & Development,Male,Manufacturing Director,6560,4,No,10,0,1,0
2,54,Research & Development,Male,Research Scientist,9184,3,No,16,8,3,3
3,35,Human Resources,Female,Manager,5282,4,No,13,12,4,2
4,34,Sales,Female,Sales Executive,5970,4,No,6,3,3,3

Output data:

0    No
1    No
2    No
3    No
4    No
Name: Attrition, dtype: object

In [ ]:
# Convert text columns into numbers
X = pd.get_dummies(X, drop_first=True)

# Convert Attrition Yes/No into 1/0
y = y.map({"Yes": 1, "No": 0})

print("Data converted successfully!")
print("Input data shape:", X.shape)

display(X.head())
print("\nTarget values:")
print(y.value_counts())

Data converted successfully!
Input data shape: (3000, 19)

,Age,MonthlyIncome,JobSatisfaction,TotalWorkingYears,YearsAtCompany,WorkLifeBalance,YearsInCurrentRole,Department_Research & Development,Department_Sales,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,OverTime_Yes
0,38,7711,1,11,0,2,0,True,False,False,False,False,False,True,False,False,False,False,False
1,44,6560,4,10,0,1,0,True,False,True,False,False,False,True,False,False,False,False,False
2,54,9184,3,16,8,3,3,True,False,True,False,False,False,False,False,True,False,False,False
3,35,5282,4,13,12,4,2,False,False,False,False,False,True,False,False,False,False,False,False
4,34,5970,4,6,3,3,3,False,True,False,False,False,False,False,False,False,True,False,False

Target values:
Attrition
0    2250
1     750
Name: count, dtype: int64

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load dataset again
df = pd.read_csv('/content/Employee_Attrition_3000_Synthetic_Records.csv.csv')

# Separate input and target
X = df.drop("Attrition", axis=1)
y = df["Attrition"].map({"Yes": 1, "No": 0})

# Convert text columns into numbers
X = pd.get_dummies(X, drop_first=True)

# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Data splitting completed successfully!")

Training data: (2400, 19)
Testing data: (600, 19)
Data splitting completed successfully!

In [ ]:
import pandas as pd

df = pd.read_csv(
    '/content/Employee_Attrition_3000_Synthetic_Records.csv.csv'
)

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

display(df.head())

Dataset loaded successfully!
Rows and columns: (3000, 12)

,Age,Attrition,Department,Gender,JobRole,MonthlyIncome,JobSatisfaction,OverTime,TotalWorkingYears,YearsAtCompany,WorkLifeBalance,YearsInCurrentRole
0,38,No,Research & Development,Female,Manufacturing Director,7711,1,No,11,0,2,0
1,44,No,Research & Development,Male,Manufacturing Director,6560,4,No,10,0,1,0
2,54,No,Research & Development,Male,Research Scientist,9184,3,No,16,8,3,3
3,35,No,Human Resources,Female,Manager,5282,4,No,13,12,4,2
4,34,No,Sales,Female,Sales Executive,5970,4,No,6,3,3,3

In [ ]:
# Separate input features and target column

X = df.drop("Attrition", axis=1)
y = df["Attrition"]

# Convert categorical columns into numeric values
X = pd.get_dummies(X, drop_first=True)

# Display the processed data
print("Encoded Dataset Shape:", X.shape)
print("\nFirst 5 Records:")
display(X.head())

Encoded Dataset Shape: (3000, 19)

First 5 Records:

,Age,MonthlyIncome,JobSatisfaction,TotalWorkingYears,YearsAtCompany,WorkLifeBalance,YearsInCurrentRole,Department_Research & Development,Department_Sales,Gender_Male,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,OverTime_Yes
0,38,7711,1,11,0,2,0,True,False,False,False,False,False,True,False,False,False,False,False
1,44,6560,4,10,0,1,0,True,False,True,False,False,False,True,False,False,False,False,False
2,54,9184,3,16,8,3,3,True,False,True,False,False,False,False,False,True,False,False,False
3,35,5282,4,13,12,4,2,False,False,False,False,False,True,False,False,False,False,False,False
4,34,5970,4,6,3,3,3,False,True,False,False,False,False,False,False,False,True,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training records:", X_train.shape[0])
print("Testing records:", X_test.shape[0])

Training records: 2400
Testing records: 600

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Create the three models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, random_state=42
    ),
    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        random_state=42
    )
}

# Train each model
for name, model in models.items():
    model.fit(X_train, y_train)
    print(name, "trained successfully!")

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression trained successfully!
Decision Tree trained successfully!
Random Forest trained successfully!

In [ ]:
# Check dataset information

print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nAttrition Distribution:")
print(df["Attrition"].value_counts())

print("\nAttrition Percentage:")
print(df["Attrition"].value_counts(normalize=True) * 100)

Dataset Shape: (3000, 12)

Missing Values:
0

Duplicate Records:
0

Attrition Distribution:
Attrition
No     2250
Yes     750
Name: count, dtype: int64

Attrition Percentage:
Attrition
No     75.0
Yes    25.0
Name: proportion, dtype: float64

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(
        random_state=42,
        class_weight="balanced"
    ),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

rf_grid.fit(X_train, y_train)

print("Best Parameters:", rf_grid.best_params_)
print("Best Cross-Validation Accuracy:",
      round(rf_grid.best_score_ * 100, 2), "%")

In [ ]:
import pandas as pd
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV

# Step 1: Load dataset
file_path = "/content/Employee_Attrition_3000_Synthetic_Records.csv.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

# Step 2: Separate features and target
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

# Step 3: Convert categorical data into numbers
X = pd.get_dummies(X, drop_first=True)

# Step 4: Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining records:", len(X_train))
print("Testing records:", len(X_test))

# Step 5: Train Random Forest with tuning
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(
        random_state=42,
        class_weight="balanced"
    ),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

rf_grid.fit(X_train, y_train)

# Step 6: Evaluate best model
best_rf = rf_grid.best_estimator_
y_pred_rf = best_rf.predict(X_test)

print("\nBest Parameters:", rf_grid.best_params_)
print("Test Accuracy:",
      round(accuracy_score(y_test, y_pred_rf) * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(
    y_test, y_pred_rf, zero_division=0
))

Dataset loaded successfully!
Dataset shape: (3000, 12)
Columns: ['Age', 'Attrition', 'Department', 'Gender', 'JobRole', 'MonthlyIncome', 'JobSatisfaction', 'OverTime', 'TotalWorkingYears', 'YearsAtCompany', 'WorkLifeBalance', 'YearsInCurrentRole']

Training records: 2400
Testing records: 600

Best Parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Test Accuracy: 75.33 %

Classification Report:
              precision    recall  f1-score   support

          No       0.76      0.98      0.86       450
         Yes       0.56      0.06      0.11       150

    accuracy                           0.75       600
   macro avg       0.66      0.52      0.48       600
weighted avg       0.71      0.75      0.67       600

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, random_state=42
    ),
    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        random_state=42
    )
}

print("MODEL ACCURACY COMPARISON")
print("-" * 35)

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    print(f"{name}: {accuracy * 100:.2f}%")

MODEL ACCURACY COMPARISON
-----------------------------------

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression: 75.67%
Decision Tree: 62.50%
Random Forest: 74.50%

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [10, 20, 30, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_
predictions = best_model.predict(X_test)

print("Best Parameters:")
print(grid.best_params_)

print("Cross-validation Accuracy:",
      round(grid.best_score_ * 100, 2), "%")

print("Test Accuracy:",
      round(accuracy_score(y_test, predictions) * 100, 2), "%")

Best Parameters:
{'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 200}
Cross-validation Accuracy: 74.87 %
Test Accuracy: 75.17 %

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# Predict using the tuned model
y_pred = best_model.predict(X_test)

print("Accuracy:",
      round(accuracy_score(y_test, y_pred) * 100, 2), "%")

print("Precision:",
      round(precision_score(
          y_test, y_pred, average="weighted", zero_division=0
      ) * 100, 2), "%")

print("Recall:",
      round(recall_score(
          y_test, y_pred, average="weighted", zero_division=0
      ) * 100, 2), "%")

print("F1 Score:",
      round(f1_score(
          y_test, y_pred, average="weighted", zero_division=0
      ) * 100, 2), "%")

print("\nDetailed Classification Report:")
print(classification_report(
    y_test, y_pred, zero_division=0
))

Accuracy: 75.17 %
Precision: 71.47 %
Recall: 75.17 %
F1 Score: 65.27 %

Detailed Classification Report:
              precision    recall  f1-score   support

          No       0.75      1.00      0.86       450
         Yes       0.60      0.02      0.04       150

    accuracy                           0.75       600
   macro avg       0.68      0.51      0.45       600
weighted avg       0.71      0.75      0.65       600

In [ ]:
import joblib

# Save the trained model
joblib.dump(best_model, "employee_attrition_model.pkl")

print("Model saved successfully!")

Model saved successfully!